import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#f7f3ea',
  },
  loginShell: {
    flex: 1,
    justifyContent: 'center',
    padding: 24,
  },
  brandBlock: {
    marginBottom: 28,
  },
  appName: {
    color: '#17191f',
    fontSize: 44,
    fontWeight: '800',
    letterSpacing: 0,
  },
  tagline: {
    color: '#4f5868',
    fontSize: 17,
    lineHeight: 25,
    marginTop: 10,
    maxWidth: 520,
  },
  loginPanel: {
    backgroundColor: '#ffffff',
    borderColor: '#e2ded4',
    borderRadius: 8,
    borderWidth: 1,
    gap: 12,
    maxWidth: 520,
    padding: 18,
  },
  label: {
    color: '#2c3340',
    fontSize: 14,
    fontWeight: '700',
  },
  input: {
    backgroundColor: '#f9fafb',
    borderColor: '#cfd6df',
    borderRadius: 8,
    borderWidth: 1,
    color: '#17191f',
    fontSize: 16,
    minHeight: 48,
    paddingHorizontal: 14,
  },
  textArea: {
    minHeight: 96,
    paddingTop: 12,
  },
  appShell: {
    flex: 1,
    marginHorizontal: 'auto',
    maxWidth: 920,
    paddingHorizontal: 18,
    paddingTop: 16,
    position: 'relative',
    width: '100%',
  },
  header: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  headerEyebrow: {
    color: '#626b7a',
    fontSize: 13,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  headerTitle: {
    color: '#17191f',
    fontSize: 30,
    fontWeight: '800',
    letterSpacing: 0,
  },
  textButton: {
    minHeight: 40,
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  textButtonLabel: {
    color: '#215d72',
    fontSize: 15,
    fontWeight: '800',
  },
  tabs: {
    backgroundColor: '#ece8de',
    borderRadius: 8,
    flexDirection: 'row',
    gap: 6,
    marginBottom: 16,
    padding: 5,
  },
  tabButton: {
    alignItems: 'center',
    borderRadius: 7,
    flex: 1,
    minHeight: 42,
    justifyContent: 'center',
  },
  activeTabButton: {
    backgroundColor: '#17191f',
  },
  tabButtonLabel: {
    color: '#4f5868',
    fontSize: 15,
    fontWeight: '800',
  },
  activeTabButtonLabel: {
    color: '#ffffff',
  },
  content: {
    paddingBottom: 96,
  },
  sectionStack: {
    gap: 16,
  },
  flashPanel: {
    backgroundColor: '#dff4e8',
    borderColor: '#a9d9bd',
    borderRadius: 8,
    borderWidth: 1,
    padding: 14,
  },
  flashText: {
    color: '#276344',
    fontSize: 16,
    fontWeight: '900',
  },
  noticePanel: {
    backgroundColor: '#dff4e8',
    borderColor: '#a9d9bd',
    borderRadius: 8,
    borderWidth: 1,
    gap: 4,
    padding: 14,
  },
  noticePanelDanger: {
    backgroundColor: '#f8e0dc',
    borderColor: '#e0aaa1',
    borderRadius: 8,
    borderWidth: 1,
    gap: 4,
    padding: 14,
  },
  noticeTitle: {
    color: '#17191f',
    fontSize: 15,
    fontWeight: '900',
  },
  noticeText: {
    color: '#3e4652',
    fontSize: 14,
    lineHeight: 20,
  },
  statusPanel: {
    backgroundColor: '#215d72',
    borderRadius: 8,
    gap: 12,
    padding: 18,
  },
  statusLabel: {
    color: '#cce8ef',
    fontSize: 13,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  statusTitle: {
    color: '#ffffff',
    fontSize: 27,
    fontWeight: '800',
    letterSpacing: 0,
  },
  statusCopy: {
    color: '#d9edf2',
    fontSize: 16,
    lineHeight: 23,
  },
  section: {
    gap: 10,
  },
  sectionTitle: {
    color: '#20242c',
    fontSize: 18,
    fontWeight: '800',
    letterSpacing: 0,
  },
  list: {
    gap: 10,
  },
  card: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#e2ded4',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    minHeight: 72,
    padding: 14,
  },
  cardHeader: {
    flex: 1,
    gap: 4,
  },
  cardTitle: {
    color: '#17191f',
    fontSize: 16,
    fontWeight: '800',
  },
  cardMeta: {
    color: '#626b7a',
    flexShrink: 1,
    fontSize: 14,
    lineHeight: 20,
  },
  progressTrack: {
    backgroundColor: '#edf0f2',
    borderRadius: 999,
    height: 8,
    marginTop: 4,
    overflow: 'hidden',
    width: '100%',
  },
  progressFill: {
    backgroundColor: '#276344',
    borderRadius: 999,
    height: 8,
  },
  progressTrackOnDark: {
    backgroundColor: '#bed8c9',
    borderRadius: 999,
    height: 10,
    marginTop: 4,
    overflow: 'hidden',
    width: '100%',
  },
  progressFillOnDark: {
    backgroundColor: '#ffffff',
    borderRadius: 999,
    height: 10,
  },
  pill: {
    backgroundColor: '#e8f3ec',
    borderRadius: 999,
    color: '#276344',
    flexShrink: 0,
    fontSize: 12,
    fontWeight: '800',
    overflow: 'hidden',
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  pillStack: {
    alignItems: 'flex-end',
    gap: 6,
  },
  dangerPill: {
    backgroundColor: '#f8e0dc',
    borderRadius: 999,
    color: '#9c2f23',
    flexShrink: 0,
    fontSize: 12,
    fontWeight: '800',
    overflow: 'hidden',
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  infoPill: {
    backgroundColor: '#dcecf2',
    borderRadius: 999,
    color: '#215d72',
    flexShrink: 0,
    fontSize: 12,
    fontWeight: '800',
    overflow: 'hidden',
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  warningPill: {
    backgroundColor: '#fff0b8',
    borderRadius: 999,
    color: '#7a5513',
    flexShrink: 0,
    fontSize: 12,
    fontWeight: '800',
    overflow: 'hidden',
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  inlinePanel: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#e2ded4',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    padding: 14,
  },
  inlineText: {
    flex: 1,
    gap: 4,
  },
  friendAvatar: {
    alignItems: 'center',
    backgroundColor: '#f1d386',
    borderRadius: 8,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  friendAvatarText: {
    color: '#31230a',
    fontSize: 18,
    fontWeight: '900',
  },
  friendDetails: {
    flex: 1,
  },
  formIntro: {
    gap: 4,
  },
  formTitle: {
    color: '#17191f',
    fontSize: 26,
    fontWeight: '900',
    letterSpacing: 0,
  },
  optionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  optionButton: {
    backgroundColor: '#ffffff',
    borderColor: '#cfd6df',
    borderRadius: 8,
    borderWidth: 1,
    minHeight: 42,
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  activeOptionButton: {
    backgroundColor: '#17191f',
    borderColor: '#17191f',
  },
  optionButtonLabel: {
    color: '#2c3340',
    fontSize: 14,
    fontWeight: '800',
  },
  activeOptionButtonLabel: {
    color: '#ffffff',
  },
  readOnlyChip: {
    backgroundColor: '#ffffff',
    borderColor: '#cfd6df',
    borderRadius: 8,
    borderWidth: 1,
    minHeight: 42,
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  readOnlyChipText: {
    color: '#2c3340',
    fontSize: 14,
    fontWeight: '800',
  },
  inputRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  inputRowField: {
    flex: 1,
  },
  taskList: {
    gap: 8,
  },
  taskItem: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#e2ded4',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    padding: 12,
  },
  completedTaskItem: {
    backgroundColor: '#dff4e8',
    borderColor: '#9fcfb4',
  },
  taskText: {
    color: '#17191f',
    flex: 1,
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 21,
  },
  completedTaskText: {
    color: '#1f563a',
  },
  removeButton: {
    minHeight: 34,
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  removeButtonLabel: {
    color: '#b33b2d',
    fontSize: 13,
    fontWeight: '900',
  },
  emptyText: {
    color: '#626b7a',
    fontSize: 14,
    fontStyle: 'italic',
  },
  summaryPanel: {
    backgroundColor: '#ffffff',
    borderColor: '#e2ded4',
    borderRadius: 8,
    borderWidth: 1,
    gap: 6,
    padding: 14,
  },
  summaryTitle: {
    color: '#17191f',
    fontSize: 17,
    fontWeight: '900',
  },
  activeSessionPanel: {
    backgroundColor: '#276344',
    borderRadius: 8,
    gap: 10,
    padding: 18,
  },
  updateItem: {
    backgroundColor: '#ffffff',
    borderColor: '#e2ded4',
    borderRadius: 8,
    borderWidth: 1,
    padding: 12,
  },
  reportItem: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#e2ded4',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    padding: 12,
  },
  reportTime: {
    color: '#215d72',
    flexShrink: 0,
    fontSize: 13,
    fontWeight: '900',
    minWidth: 72,
  },
  dangerPanel: {
    backgroundColor: '#fff7f5',
    borderColor: '#e0aaa1',
    borderRadius: 8,
    borderWidth: 1,
    gap: 10,
    padding: 14,
  },
  dangerTitle: {
    color: '#9c2f23',
    fontSize: 17,
    fontWeight: '900',
  },
  actionRow: {
    flexDirection: 'row',
    gap: 10,
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: '#d94f35',
    borderRadius: 8,
    flex: 1,
    minHeight: 48,
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
  pressedButton: {
    opacity: 0.86,
  },
  disabledButton: {
    backgroundColor: '#aeb6c2',
  },
  primaryButtonLabel: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '900',
  },
  secondaryButton: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#cfd6df',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    minHeight: 48,
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
  secondaryButtonLabel: {
    color: '#2c3340',
    fontSize: 16,
    fontWeight: '900',
  },
  smallButton: {
    alignItems: 'center',
    backgroundColor: '#17191f',
    borderRadius: 8,
    minHeight: 42,
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
  smallButtonLabel: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '900',
  },
  floatingActionButton: {
    alignItems: 'center',
    backgroundColor: '#d94f35',
    borderRadius: 999,
    bottom: 18,
    minHeight: 56,
    justifyContent: 'center',
    paddingHorizontal: 22,
    position: 'absolute',
    right: 18,
    shadowColor: '#17191f',
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 0.18,
    shadowRadius: 16,
  },
  floatingActionButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '900',
  },
  centerOverlay: {
    alignItems: 'center',
    backgroundColor: 'rgba(23, 25, 31, 0.28)',
    bottom: 0,
    justifyContent: 'center',
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  centerPopup: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#e2ded4',
    borderRadius: 8,
    borderWidth: 1,
    gap: 14,
    maxWidth: 320,
    padding: 20,
    width: '86%',
  },
  centerPopupTitle: {
    color: '#17191f',
    fontSize: 22,
    fontWeight: '900',
    letterSpacing: 0,
    textAlign: 'center',
  },
  centerPopupButton: {
    alignItems: 'center',
    backgroundColor: '#17191f',
    borderRadius: 8,
    minHeight: 42,
    justifyContent: 'center',
    paddingHorizontal: 18,
    width: '100%',
  },
  centerPopupButtonText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '900',
  },
});
